name: recipe_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # PASTIKAN SEMUA PAKET INI SEJAJAR (INDENTASINYA SAMA)
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_riverpod: ^2.5.1
  lottie: ^3.1.2 # Paket untuk animasi Lottie
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # DAFTARKAN SEMUA FOLDER ASET ANDA DI SINI
  assets:
    - assets/data/users.json   